Repository ichor-dev/ichor, pull requests merged in 2023-08, with the labels that each got.

#14 remove usage of compressed/uncompressed buffer function
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/extensions/bytes/ByteBufferExtensions.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/networking/packet/incoming/IncomingPacketHandler.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/networking/packet/outgoing/configuration/Disconnect.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/networking/packet/outgoing/configuration/FeatureFlags.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/networking/packet/outgoing/configuration/FinishConfiguration.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/networking/packet/outgoing/configuration/KeepAlive.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/networking/packet/outgoing/configuration/Ping.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/networking/packet/outgoing/configuration/PluginMessage.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/networking/packet/outgoing/configuration/RegistryData.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/networking/packet/outgoing/configuration/ResourcePack.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/networking/packet/outgoing/configuration/UpdateTags.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/networking/packet/outgoing/login/EncryptionRequest.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/networking/packet/outgoing/login/LoginDisconnect.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/networking/packet/outgoing/login/LoginPluginRequest.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/networking/packet/outgoing/login/LoginSuccess.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/networking/packet/outgoing/login/SetCompression.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/networking/packet/outgoing/status/PingResponse.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/networking/packet/outgoing/status/StatusResponse.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/networking/packet/receive/receivers/login/EncryptionResponseReceiver.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/networking/packet/receive/receivers/status/PingRequestReceiver.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/networking/packet/receive/receivers/status/StatusRequestReceiver.kt
Labels: refactoring

#17 rework ByteBuffer serialization
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/extensions/bytes/ByteBufferExtensions.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/extensions/bytes/ByteExtensions.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/extensions/bytes/buffer/CustomBufferExtensions.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/extensions/bytes/buffer/NumberBufferExtensions.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/extensions/bytes/buffer/PrimitiveBufferExtensions.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/models/nbt/Tag.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/models/nbt/TagType.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/models/nbt/impl/ByteTag.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/models/nbt/impl/CompoundTag.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/models/nbt/impl/DoubleTag.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/models/nbt/impl/FloatTag.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/models/nbt/impl/IntArrayTag.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/models/nbt/impl/IntTag.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/models/nbt/impl/ListTag.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/models/nbt/impl/LongArrayTag.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/models/nbt/impl/LongTag.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/models/nbt/impl/ShortTag.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/models/nbt/impl/StringTag.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/networking/DataTypes.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/networking/packet/incoming/IncomingPacketHandler.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/networking/packet/incoming/configuration/KeepAlive.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/networking/packet/incoming/configuration/PluginMessage.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/networking/packet/incoming/configuration/Pong.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/networking/packet/incoming/configuration/ResourcePackResponse.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/networking/packet/incoming/handshaking/Handshake.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/networking/packet/incoming/login/EncryptionResponse.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/networking/packet/incoming/login/LoginStart.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/networking/packet/incoming/login/PluginMessageResponse.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/networking/packet/incoming/status/PingRequest.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/networking/packet/outgoing/configuration/Disconnect.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/networking/packet/outgoing/configuration/FeatureFlags.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/networking/packet/outgoing/configuration/KeepAlive.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/networking/packet/outgoing/configuration/Ping.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/networking/packet/outgoing/configuration/PluginMessage.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/networking/packet/outgoing/configuration/RegistryData.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/networking/packet/outgoing/configuration/ResourcePack.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/networking/packet/outgoing/configuration/UpdateTags.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/networking/packet/outgoing/login/EncryptionRequest.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/networking/packet/outgoing/login/LoginDisconnect.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/networking/packet/outgoing/login/LoginPluginRequest.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/networking/packet/outgoing/login/LoginSuccess.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/networking/packet/outgoing/login/SetCompression.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/networking/packet/outgoing/status/PingResponse.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/networking/packet/outgoing/status/StatusResponse.kt
  gaia/src/test/kotlin/fyi/pauli/ichor/gaia/tests/ByteBufferCustomExtensionTests.kt
  gaia/src/test/kotlin/fyi/pauli/ichor/gaia/tests/ByteBufferExtensionTests.kt
  gaia/src/test/kotlin/fyi/pauli/ichor/gaia/tests/ByteBufferNumberExtensionTests.kt
  gaia/src/test/kotlin/fyi/pauli/ichor/gaia/tests/ByteBufferPrimitiveExtensionTests.kt
Labels: enhancement, refactoring

#20 move server socket to gaia
  .github/ISSUE_TEMPLATE/bug_report.md
  CODE_OF_CONDUCT.md
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/entity/player/UserProfile.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/models/nbt/Tag.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/models/payload/BrandPayload.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/networking/packet/PacketHandle.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/networking/packet/incoming/IncomingPacket.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/networking/packet/outgoing/configuration/FeatureFlags.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/networking/packet/outgoing/configuration/FinishConfiguration.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/networking/packet/outgoing/configuration/KeepAlive.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/networking/packet/outgoing/configuration/Ping.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/networking/packet/outgoing/configuration/PluginMessage.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/networking/packet/outgoing/configuration/RegistryData.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/networking/packet/outgoing/configuration/ResourcePack.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/networking/packet/outgoing/configuration/UpdateTags.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/networking/packet/outgoing/login/LoginDisconnect.kt
  gaia/src/main/kotlin/fyi/pauli/ichor/gaia/server/Server.kt
  gaia/src/test/kotlin/fyi/pauli/ichor/gaia/tests/ByteBufferPrimitiveExtensionTests.kt
  hephaistos/src/main/kotlin/fyi/pauli/ichor/hephaistos/Hephaistos.kt
  hephaistos/src/main/kotlin/fyi/pauli/ichor/hephaistos/networking/receivers/HephaistosReceiverHelper.kt
  hephaistos/src/main/kotlin/fyi/pauli/ichor/hephaistos/networking/receivers/handshaking/HandshakeReceiver.kt
  hephaistos/src/main/kotlin/fyi/pauli/ichor/hephaistos/networking/receivers/login/LoginStartReceiver.kt
  hephaistos/src/main/kotlin/fyi/pauli/ichor/hephaistos/networking/receivers/status/PingRequestReceiver.kt
Labels: idea, refactoring
